import React from "react";
import SEO from "../SEO";
import AnalysisDisclaimer from "./AnalysisDisclaimer";
import type { AnalysisData } from "../../types/analysis";

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="mb-14"><h2 className="text-2xl md:text-3xl font-serif font-bold text-foreground mb-5">{title}</h2>{children}</section>;
const Table = ({ children }: { children: React.ReactNode }) => <div className="overflow-x-auto rounded-xl border border-border"><table className="min-w-full text-sm">{children}</table></div>;
const Head = ({ children }: { children: React.ReactNode }) => <thead className="bg-muted/60 text-left text-xs uppercase tracking-wider text-muted-foreground">{children}</thead>;
const Row = ({ children }: { children: React.ReactNode }) => <tr className="border-t border-border/70 [&>td]:p-3 [&>td]:align-top">{children}</tr>;

export default function MetaDeepDive({ data }: { data: AnalysisData }) {
  return <main className="bg-background min-h-screen pt-28 pb-24"><SEO title="Meta Platforms – analys" description={data.summary} canonical="https://www.borsanalys.se/analyser/meta" />
    <article className="max-w-5xl mx-auto px-5 md:px-8">
      <header className="mb-12 border-b border-border pb-8"><p className="text-sm font-bold uppercase tracking-widest text-primary">Nasdaq · META · 31 juli 2026</p><h1 className="mt-3 text-4xl md:text-6xl font-serif font-bold">Meta Platforms</h1><p className="mt-4 text-lg text-muted-foreground max-w-3xl">En stark annonsmotor möter högre AI- och datacentercapex. Frågan är när fria kassaflöden återhämtar sig.</p><div className="mt-6 grid grid-cols-2 md:grid-cols-4 gap-3"><div className="rounded-xl bg-card border border-border p-4"><b>BEVAKA</b><br/><span className="text-sm text-muted-foreground">Rekommendation</span></div><div className="rounded-xl bg-card border border-border p-4"><b>25/35</b><br/><span className="text-sm text-muted-foreground">Totalrating</span></div><div className="rounded-xl bg-card border border-border p-4"><b>612,50 USD</b><br/><span className="text-sm text-muted-foreground">12 mån. värde</span></div><div className="rounded-xl bg-card border border-border p-4"><b>1 066,05 USD</b><br/><span className="text-sm text-muted-foreground">5 år, viktat</span></div></div></header>
      <AnalysisDisclaimer />
      <Section title="Snabböversikt"><Table><tbody><Row><td>Aktuell kurs</td><td>556,71 USD</td><td>Risknivå</td><td>Hög</td></Row><Row><td>Bolagskvalitet</td><td>16/20</td><td>Investeringsattraktivitet</td><td>9/15</td></Row><Row><td>Tolvmånaderszon</td><td>Rimligt värderad</td><td>Femårszon</td><td>Rimligt värderad</td></Row></tbody></Table></Section>
      <Section title="Investeringstes på 30 sekunder"><Table><Head><tr><th className="p-3">Fråga</th><th className="p-3">Slutsats</th></tr></Head><tbody><Row><td>Attraktivitet</td><td>Global, skalbar annonsplattform med hög FoA-lönsamhet.</td></Row><Row><td>Största risk</td><td>AI- och datacenterinvesteringar kan ge låg avkastning och pressa FCF.</td></Row><Row><td>Bekräftelse</td><td>Högre annonspris, impressions, stabil marginal och FCF-återhämtning.</td></Row></tbody></Table></Section>
      <Section title="Företagsöversikt och ledning"><Table><tbody><Row><td>VD / ordförande</td><td>Mark Zuckerberg</td><td>CFO</td><td>Susan Li</td></Row><Row><td>Huvudkontor</td><td>Menlo Park, Kalifornien</td><td>Anställda</td><td>75 472</td></Row><Row><td>Illustrativt börsvärde</td><td>1 413,2 md USD</td><td>Illustrativ EV</td><td>1 435,2 md USD</td></Row></tbody></Table><p className="mt-4 text-muted-foreground">Återköp sker, men aktieantalet ökar i samtliga scenarier eftersom SBC-utspädningen överstiger återköpta aktier.</p></Section>
      <Section title="Affärsmodell och intäktsflöde"><Table><Head><tr><th className="p-3">Q2 2026</th><th className="p-3">Omsättning</th><th className="p-3">Tillväxt</th><th className="p-3">Segmentresultat</th></tr></Head><tbody><Row><td>Family of Apps</td><td>60,370 md USD</td><td>28 %</td><td>23,394 md USD</td></Row><Row><td>Reality Labs</td><td>0,431 md USD</td><td>16 %</td><td>−4,619 md USD</td></Row><Row><td>Koncernen</td><td>60,801 md USD</td><td>28 %</td><td>18,775 md USD</td></Row></tbody></Table><p className="mt-4 text-muted-foreground">Advertising stod för 97,6 % av omsättningen. Reality Labs är en separat förlustverksamhet.</p></Section>
      <Section title="Finansiell utveckling och vinstkvalitet"><Table><Head><tr><th className="p-3">Md USD</th>{[2021,2022,2023,2024,2025].map(y=><th key={y} className="p-3">FY{y}</th>)}</tr></Head><tbody><Row><td>Revenue</td><td>117,929</td><td>116,609</td><td>134,902</td><td>164,501</td><td>200,966</td></Row><Row><td>EBIT</td><td>46,753</td><td>28,944</td><td>46,751</td><td>69,380</td><td>83,276</td></Row><Row><td>OCF</td><td>57,683</td><td>50,475</td><td>71,113</td><td>91,328</td><td>115,800</td></Row><Row><td>FCF</td><td>38,439</td><td>18,439</td><td>43,010</td><td>52,103</td><td>43,584</td></Row></tbody></Table><p className="mt-4 text-muted-foreground">FCF = OCF − purchases of property and equipment − principal payments on finance leases.</p></Section>
      <Section title="NTM-modell — Börsanalys.se-estimat"><Table><Head><tr><th className="p-3">Md USD, utom VPA</th><th className="p-3">Q3 2026</th><th className="p-3">Q4 2026</th><th className="p-3">Q1 2027</th><th className="p-3">Q2 2027</th></tr></Head><tbody><Row><td>Revenue</td><td>62,50</td><td>73,00</td><td>66,50</td><td>73,00</td></Row><Row><td>EBIT-marginal</td><td>34,0 %</td><td>34,5 %</td><td>35,0 %</td><td>35,5 %</td></Row><Row><td>VPA</td><td>6,78</td><td>8,05</td><td>7,42</td><td>8,27</td></Row><Row><td>FCF</td><td>−3,42</td><td>−15,34</td><td>−4,24</td><td>−4,63</td></Row></tbody></Table><p className="mt-4 text-muted-foreground">NTM-VPA: 30,52 USD. Q4-capex om 51,58 md USD är ett residual estimate.</p></Section>
      <Section title="Scorecard"><Table><tbody>{[["Företagsöversikt och ledning","4/5"],["Affärsmodell","5/5"],["Konkurrensfördelar","4/5"],["Finansiell kvalitet","3/5"],["Fundamental värdering","3/5"],["Potentiella kursdrivare","4/5"],["Riskprofil, inverterad","2/5"]].map(([n,s])=><Row key={n}><td>{n}</td><td>{s}</td></Row>)}</tbody></Table></Section>
      <Section title="Fundamental värdering"><Table><tbody><Row><td>NTM-VPA / NTM P/E</td><td>30,52 USD / 18,24×</td></Row><Row><td>Illustrativ EV / EV-EBIT</td><td>1 435,2 md USD / 16,51×</td></Row><Row><td>12 månaders huvudankare</td><td>612,50 USD</td></Row></tbody></Table><Table><Head><tr><th className="p-3">Scenario</th><th className="p-3">Sannolikhet</th><th className="p-3">2031 VPA</th><th className="p-3">P/E</th><th className="p-3">Totalvärde</th><th className="p-3">CAGR</th></tr></Head><tbody><Row><td>Bear</td><td>30 %</td><td>33,39</td><td>18×</td><td>611,44 USD</td><td>1,75 %</td></Row><Row><td>Base</td><td>50 %</td><td>49,78</td><td>22×</td><td>1 107,87 USD</td><td>13,54 %</td></Row><Row><td>Bull</td><td>20 %</td><td>62,62</td><td>26×</td><td>1 643,40 USD</td><td>22,11 %</td></Row></tbody></Table><p className="mt-4 font-semibold">Sannolikhetsvägt totalvärde: 1 066,05 USD · CAGR: 12,73 %</p></Section>
      <Section title="Kurszoner och investeringsbeslut"><Table><Head><tr><th className="p-3">Zon</th><th className="p-3">12 månader</th><th className="p-3">Fem år</th></tr></Head><tbody><Row><td>Extremt köpvärd</td><td>Under 510 USD</td><td>Under 397 USD</td></Row><Row><td>Köpvärd</td><td>510–533 USD</td><td>397–500 USD</td></Row><Row><td>Rimligt värderad</td><td>533–567 USD</td><td>500–702 USD</td></Row><Row><td>Fullvärderad</td><td>567–613 USD</td><td>702–1 066 USD</td></Row><Row><td>Säljzon</td><td>Över 613 USD</td><td>Över 1 066 USD</td></Row></tbody></Table><h2 className="mt-8 text-3xl font-serif font-bold">BEVAKA</h2><p className="mt-3 text-muted-foreground">Hög bolagskvalitet och rimlig värdering vägs mot hög kapitalintensitet, svag kortsiktig FCF och osäkerhet kring AI-avkastning.</p></Section>
    </article></main>;
}
